# All paths are relative to current working directory

WORKDIR = work

CCDONE = $(addprefix $(WORKDIR)/, $(SRCS:=.ccdone))

$(WORKDIR)/%.v.ccdone: %.v
	vlog $< && touch $@

$(WORKDIR)/%.vhd.ccdone: %.vhd
	vcom $< && touch $@

$(WORKDIR)/%.vhdl.ccdone: %.vhdl
	vcom $< && touch $@

bsimu: $(CCDONE)
	( echo vcd file; echo run -all ) | vsim -c $(TOP)

compile: $(CCDONE)
	quartus_sh --flow compile $(TOP)

clean:
	rm -rf $(WORKDIR) transcript
